import { ServiceCategory } from "@/types";

export const serviceCategories: ServiceCategory[] = [
  {
    id: "bank-liquidation",
    title: "Bank Liquidation",
    slug: "bank-liquidation",
    description:
      "High-security vaults, safes, and equipment from decommissioned financial institutions. We specialize in acquiring and repurposing bank-grade security infrastructure.",
    coverImage: "/images/galleries/bank-liquidation/bank-1.jpg",
    images: [
      { id: "bank-1", url: "/images/galleries/bank-liquidation/bank-1.jpg", alt: "Bank security vault" },
      { id: "bank-2", url: "/images/galleries/bank-liquidation/bank-2.jpg", alt: "Bank vault door system" },
      { id: "bank-3", url: "/images/galleries/bank-liquidation/bank-3.jpg", alt: "Commercial bank safe" },
      { id: "bank-4", url: "/images/galleries/bank-liquidation/bank-4.jpg", alt: "Bank liquidation safe" },
      { id: "bank-5", url: "/images/galleries/bank-liquidation/bank-5.jpg", alt: "High-security vault door" },
      { id: "bank-6", url: "/images/galleries/bank-liquidation/bank-6.jpg", alt: "Bank safe deposit system" },
      { id: "bank-7", url: "/images/galleries/bank-liquidation/bank-7.jpg", alt: "Vault security mechanism" },
      { id: "bank-8", url: "/images/galleries/bank-liquidation/bank-8.jpg", alt: "Bank-grade safe" },
      { id: "bank-9", url: "/images/galleries/bank-liquidation/bank-9.jpg", alt: "Security vault installation" },
      { id: "bank-10", url: "/images/galleries/bank-liquidation/bank-10.jpg", alt: "Commercial vault door" },
      { id: "bank-12", url: "/images/galleries/bank-liquidation/bank-12.jpg", alt: "High-security safe system" },
      { id: "bank-13", url: "/images/galleries/bank-liquidation/bank-13.jpg", alt: "Bank vault interior" },
      { id: "bank-14", url: "/images/galleries/bank-liquidation/bank-14.jpg", alt: "Safe deposit box array" },
      { id: "bank-15", url: "/images/galleries/bank-liquidation/bank-15.jpg", alt: "Vault door mechanism" },
      { id: "bank-16", url: "/images/galleries/bank-liquidation/bank-16.jpg", alt: "Bank security system" },
      { id: "bank-17", url: "/images/galleries/bank-liquidation/bank-17.jpg", alt: "Commercial safe installation" },
      { id: "bank-18", url: "/images/galleries/bank-liquidation/bank-18.jpg", alt: "Bank vault components" },
      { id: "bank-19", url: "/images/galleries/bank-liquidation/bank-19.jpg", alt: "Security vault door" },
      { id: "bank-20", url: "/images/galleries/bank-liquidation/bank-20.jpg", alt: "Bank-grade security equipment" },
      { id: "bank-21", url: "/images/galleries/bank-liquidation/bank-21.jpg", alt: "Vault locking system" },
      { id: "bank-22", url: "/images/galleries/bank-liquidation/bank-22.jpg", alt: "Bank safe liquidation" },
      { id: "bank-23", url: "/images/galleries/bank-liquidation/bank-23.jpg", alt: "High-security vault" },
      { id: "bank-24", url: "/images/galleries/bank-liquidation/bank-24.jpg", alt: "Commercial bank vault" },
      { id: "bank-25", url: "/images/galleries/bank-liquidation/bank-25.jpg", alt: "Bank security door" },
      { id: "bank-26", url: "/images/galleries/bank-liquidation/bank-26.jpg", alt: "Vault safe system" },
      { id: "bank-27", url: "/images/galleries/bank-liquidation/bank-27.jpg", alt: "Bank liquidation vault" },
      { id: "bank-28", url: "/images/galleries/bank-liquidation/bank-28.jpg", alt: "Security safe installation" },
      { id: "bank-29", url: "/images/galleries/bank-liquidation/bank-29.jpg", alt: "Bank vault door assembly" },
      { id: "bank-30", url: "/images/galleries/bank-liquidation/bank-30.jpg", alt: "Commercial safe system" },
      { id: "bank-31", url: "/images/galleries/bank-liquidation/bank-31.jpg", alt: "Bank security vault door" },
      { id: "bank-32", url: "/images/galleries/bank-liquidation/bank-32.jpg", alt: "High-security safe" },
      { id: "bank-33", url: "/images/galleries/bank-liquidation/bank-33.jpg", alt: "Bank vault equipment" },
      { id: "bank-34", url: "/images/galleries/bank-liquidation/bank-34.jpg", alt: "Vault security system" },
      { id: "bank-35", url: "/images/galleries/bank-liquidation/bank-35.jpg", alt: "Bank liquidation safe door" },
      { id: "bank-36", url: "/images/galleries/bank-liquidation/bank-36.jpg", alt: "Commercial vault system" },
      { id: "bank-37", url: "/images/galleries/bank-liquidation/bank-37.jpg", alt: "Bank-grade vault door" },
      { id: "bank-38", url: "/images/galleries/bank-liquidation/bank-38.jpg", alt: "Security vault installation" },
      { id: "bank-39", url: "/images/galleries/bank-liquidation/bank-39.jpg", alt: "Bank safe equipment" },
    ],
  },
  {
    id: "panic-safe-rooms",
    title: "Panic & Safe Rooms",
    slug: "panic-safe-rooms",
    description:
      "Custom-built secure rooms designed for emergency protection. Integrated seamlessly into your home or business with reinforced walls, communication systems, and air filtration.",
    coverImage: "/images/galleries/panic-safe-rooms/panic-1.jpg",
    images: [
      { id: "panic-1", url: "/images/galleries/panic-safe-rooms/panic-1.jpg", alt: "Panic room entrance" },
      { id: "panic-2", url: "/images/galleries/panic-safe-rooms/panic-2.jpg", alt: "Safe room door system" },
      { id: "panic-3", url: "/images/galleries/panic-safe-rooms/panic-3.jpg", alt: "Residential panic room" },
      { id: "panic-4", url: "/images/galleries/panic-safe-rooms/panic-4.jpg", alt: "Safe room interior" },
      { id: "panic-5", url: "/images/galleries/panic-safe-rooms/panic-5.jpg", alt: "Panic room security door" },
      { id: "panic-6", url: "/images/galleries/panic-safe-rooms/panic-6.jpg", alt: "Commercial safe room" },
      { id: "panic-7", url: "/images/galleries/panic-safe-rooms/panic-7.jpg", alt: "Reinforced panic room" },
      { id: "panic-8", url: "/images/galleries/panic-safe-rooms/panic-8.jpg", alt: "Safe room installation" },
      { id: "panic-9", url: "/images/galleries/panic-safe-rooms/panic-9.jpg", alt: "Panic room door mechanism" },
      { id: "panic-10", url: "/images/galleries/panic-safe-rooms/panic-10.jpg", alt: "Secure room system" },
      { id: "panic-11", url: "/images/galleries/panic-safe-rooms/panic-11.jpg", alt: "Panic room construction" },
      { id: "panic-12", url: "/images/galleries/panic-safe-rooms/panic-12.jpg", alt: "Safe room vault door" },
      { id: "panic-13", url: "/images/galleries/panic-safe-rooms/panic-13.jpg", alt: "Residential safe room" },
      { id: "panic-14", url: "/images/galleries/panic-safe-rooms/panic-14.jpg", alt: "Panic room security" },
      { id: "panic-15", url: "/images/galleries/panic-safe-rooms/panic-15.jpg", alt: "Safe room design" },
      { id: "panic-16", url: "/images/galleries/panic-safe-rooms/panic-16.jpg", alt: "Panic room door installation" },
      { id: "panic-17", url: "/images/galleries/panic-safe-rooms/panic-17.jpg", alt: "Secure panic room" },
      { id: "panic-18", url: "/images/galleries/panic-safe-rooms/panic-18.jpg", alt: "Safe room entrance" },
      { id: "panic-19", url: "/images/galleries/panic-safe-rooms/panic-19.jpg", alt: "Commercial panic room" },
      { id: "panic-20", url: "/images/galleries/panic-safe-rooms/panic-20.jpg", alt: "Panic room vault" },
      { id: "panic-21", url: "/images/galleries/panic-safe-rooms/panic-21.jpg", alt: "Safe room security system" },
      { id: "panic-22", url: "/images/galleries/panic-safe-rooms/panic-22.jpg", alt: "Reinforced safe room" },
      { id: "panic-23", url: "/images/galleries/panic-safe-rooms/panic-23.jpg", alt: "Panic room door" },
      { id: "panic-24", url: "/images/galleries/panic-safe-rooms/panic-24.jpg", alt: "Secure room construction" },
      { id: "panic-25", url: "/images/galleries/panic-safe-rooms/panic-25.jpg", alt: "Safe room installation" },
      { id: "panic-26", url: "/images/galleries/panic-safe-rooms/panic-26.jpg", alt: "Panic room interior design" },
      { id: "panic-27", url: "/images/galleries/panic-safe-rooms/panic-27.jpg", alt: "Safe room door system" },
      { id: "panic-28", url: "/images/galleries/panic-safe-rooms/panic-28.jpg", alt: "Residential panic room door" },
      { id: "panic-29", url: "/images/galleries/panic-safe-rooms/panic-29.jpg", alt: "Panic room security door" },
      { id: "panic-30", url: "/images/galleries/panic-safe-rooms/panic-30.jpg", alt: "Commercial safe room system" },
      { id: "panic-31", url: "/images/galleries/panic-safe-rooms/panic-31.jpg", alt: "Panic room vault door" },
      { id: "panic-32", url: "/images/galleries/panic-safe-rooms/panic-32.jpg", alt: "Safe room entrance door" },
      { id: "panic-33", url: "/images/galleries/panic-safe-rooms/panic-33.jpg", alt: "Secure panic room design" },
      { id: "panic-34", url: "/images/galleries/panic-safe-rooms/panic-34.jpg", alt: "Panic room construction" },
      { id: "panic-35", url: "/images/galleries/panic-safe-rooms/panic-35.jpg", alt: "Safe room security door" },
      { id: "panic-36", url: "/images/galleries/panic-safe-rooms/panic-36.jpg", alt: "Reinforced panic room door" },
      { id: "panic-37", url: "/images/galleries/panic-safe-rooms/panic-37.jpg", alt: "Panic room installation" },
      { id: "panic-38", url: "/images/galleries/panic-safe-rooms/panic-38.jpg", alt: "Safe room vault system" },
      { id: "panic-39", url: "/images/galleries/panic-safe-rooms/panic-39.jpg", alt: "Commercial panic room door" },
      { id: "panic-40", url: "/images/galleries/panic-safe-rooms/panic-40.jpg", alt: "Panic room security installation" },
      { id: "panic-41", url: "/images/galleries/panic-safe-rooms/panic-41.jpg", alt: "Safe room door design" },
      { id: "panic-42", url: "/images/galleries/panic-safe-rooms/panic-42.jpg", alt: "Residential safe room door" },
      { id: "panic-43", url: "/images/galleries/panic-safe-rooms/panic-43.jpg", alt: "Panic room vault construction" },
      { id: "panic-44", url: "/images/galleries/panic-safe-rooms/panic-44.jpg", alt: "Secure safe room" },
      { id: "panic-45", url: "/images/galleries/panic-safe-rooms/panic-45.jpg", alt: "Panic room door mechanism" },
      { id: "panic-46", url: "/images/galleries/panic-safe-rooms/panic-46.jpg", alt: "Safe room security design" },
      { id: "panic-47", url: "/images/galleries/panic-safe-rooms/panic-47.jpg", alt: "Commercial safe room door" },
      { id: "panic-48", url: "/images/galleries/panic-safe-rooms/panic-48.jpg", alt: "Panic room installation system" },
    ],
  },
  {
    id: "bunkers",
    title: "Bunkers & Bomb Shelters",
    slug: "bunkers",
    description:
      "Underground fortifications engineered for ultimate survival. Custom-designed bunkers with life support systems, security features, and comfortable living spaces.",
    coverImage: "/images/galleries/bunkers/bunker-1.jpg",
    images: [
      { id: "bunker-1", url: "/images/galleries/bunkers/bunker-1.jpg", alt: "Underground bunker entrance" },
      { id: "bunker-2", url: "/images/galleries/bunkers/bunker-2.jpg", alt: "Bunker interior space" },
      { id: "bunker-3", url: "/images/galleries/bunkers/bunker-3.jpg", alt: "Bomb shelter construction" },
      { id: "bunker-4", url: "/images/galleries/bunkers/bunker-4.jpg", alt: "Bunker entrance door" },
      { id: "bunker-5", url: "/images/galleries/bunkers/bunker-5.jpg", alt: "Underground shelter system" },
      { id: "bunker-6", url: "/images/galleries/bunkers/bunker-6.jpg", alt: "Bunker living quarters" },
      { id: "bunker-7", url: "/images/galleries/bunkers/bunker-7.jpg", alt: "Bomb shelter door" },
      { id: "bunker-8", url: "/images/galleries/bunkers/bunker-8.jpg", alt: "Bunker security entrance" },
      { id: "bunker-9", url: "/images/galleries/bunkers/bunker-9.jpg", alt: "Underground bunker construction" },
      { id: "bunker-10", url: "/images/galleries/bunkers/bunker-10.jpg", alt: "Bunker ventilation system" },
      { id: "bunker-11", url: "/images/galleries/bunkers/bunker-11.jpg", alt: "Bomb shelter installation" },
      { id: "bunker-12", url: "/images/galleries/bunkers/bunker-12.jpg", alt: "Bunker entrance tunnel" },
      { id: "bunker-13", url: "/images/galleries/bunkers/bunker-13.jpg", alt: "Underground shelter door" },
      { id: "bunker-14", url: "/images/galleries/bunkers/bunker-14.jpg", alt: "Bunker interior design" },
      { id: "bunker-15", url: "/images/galleries/bunkers/bunker-15.jpg", alt: "Bomb shelter security" },
      { id: "bunker-16", url: "/images/galleries/bunkers/bunker-16.jpg", alt: "Bunker access system" },
      { id: "bunker-17", url: "/images/galleries/bunkers/bunker-17.jpg", alt: "Underground bunker facility" },
      { id: "bunker-18", url: "/images/galleries/bunkers/bunker-18.jpg", alt: "Bunker storage area" },
      { id: "bunker-19", url: "/images/galleries/bunkers/bunker-19.jpg", alt: "Bomb shelter construction" },
      { id: "bunker-20", url: "/images/galleries/bunkers/bunker-20.jpg", alt: "Bunker entrance hallway" },
      { id: "bunker-21", url: "/images/galleries/bunkers/bunker-21.jpg", alt: "Underground shelter entrance" },
      { id: "bunker-22", url: "/images/galleries/bunkers/bunker-22.jpg", alt: "Bunker safety door" },
      { id: "bunker-23", url: "/images/galleries/bunkers/bunker-23.jpg", alt: "Bomb shelter design" },
      { id: "bunker-24", url: "/images/galleries/bunkers/bunker-24.jpg", alt: "Bunker living space" },
      { id: "bunker-25", url: "/images/galleries/bunkers/bunker-25.jpg", alt: "Underground bunker door" },
      { id: "bunker-26", url: "/images/galleries/bunkers/bunker-26.jpg", alt: "Bunker security system" },
      { id: "bunker-27", url: "/images/galleries/bunkers/bunker-27.jpg", alt: "Bomb shelter entrance" },
      { id: "bunker-28", url: "/images/galleries/bunkers/bunker-28.jpg", alt: "Bunker ventilation design" },
      { id: "bunker-29", url: "/images/galleries/bunkers/bunker-29.jpg", alt: "Underground shelter construction" },
      { id: "bunker-30", url: "/images/galleries/bunkers/bunker-30.jpg", alt: "Bunker access door" },
      { id: "bunker-31", url: "/images/galleries/bunkers/bunker-31.jpg", alt: "Bomb shelter interior" },
      { id: "bunker-32", url: "/images/galleries/bunkers/bunker-32.jpg", alt: "Bunker entrance system" },
      { id: "bunker-33", url: "/images/galleries/bunkers/bunker-33.jpg", alt: "Underground bunker hallway" },
      { id: "bunker-34", url: "/images/galleries/bunkers/bunker-34.jpg", alt: "Bunker storage system" },
      { id: "bunker-35", url: "/images/galleries/bunkers/bunker-35.jpg", alt: "Bomb shelter door system" },
      { id: "bunker-36", url: "/images/galleries/bunkers/bunker-36.jpg", alt: "Bunker living area" },
      { id: "bunker-37", url: "/images/galleries/bunkers/bunker-37.jpg", alt: "Underground shelter design" },
      { id: "bunker-38", url: "/images/galleries/bunkers/bunker-38.jpg", alt: "Bunker security entrance" },
      { id: "bunker-39", url: "/images/galleries/bunkers/bunker-39.jpg", alt: "Bomb shelter facility" },
      { id: "bunker-40", url: "/images/galleries/bunkers/bunker-40.jpg", alt: "Bunker construction project" },
      { id: "bunker-41", url: "/images/galleries/bunkers/bunker-41.jpg", alt: "Underground bunker system" },
      { id: "bunker-42", url: "/images/galleries/bunkers/bunker-42.jpg", alt: "Bunker installation complete" },
    ],
  },
  {
    id: "bulletproof-glass",
    title: "Bulletproof Glass",
    slug: "bulletproof-glass",
    description:
      "Military-grade transparent armor for windows, doors, and partitions. Ballistic-rated glass that provides protection without compromising visibility.",
    coverImage: "/images/galleries/bulletproof-glass/glass-1.png",
    images: [
      { id: "glass-1", url: "/images/galleries/bulletproof-glass/glass-1.png", alt: "Bulletproof glass installation" },
      { id: "glass-2", url: "/images/galleries/bulletproof-glass/glass-2.png", alt: "Ballistic glass panel" },
      { id: "glass-3", url: "/images/galleries/bulletproof-glass/glass-3.png", alt: "Commercial bulletproof glass" },
      { id: "glass-4", url: "/images/galleries/bulletproof-glass/glass-4.png", alt: "Bulletproof window system" },
      { id: "glass-5", url: "/images/galleries/bulletproof-glass/glass-5.png", alt: "Military-grade glass" },
      { id: "glass-6", url: "/images/galleries/bulletproof-glass/glass-6.png", alt: "Ballistic-rated glass door" },
      { id: "glass-7", url: "/images/galleries/bulletproof-glass/glass-7.png", alt: "Transparent armor panel" },
      { id: "glass-8", url: "/images/galleries/bulletproof-glass/glass-8.png", alt: "Bulletproof glass partition" },
      { id: "glass-9", url: "/images/galleries/bulletproof-glass/glass-9.png", alt: "Security glass installation" },
      { id: "glass-10", url: "/images/galleries/bulletproof-glass/glass-10.png", alt: "Ballistic glass window" },
      { id: "glass-11", url: "/images/galleries/bulletproof-glass/glass-11.png", alt: "Bulletproof glass design" },
      { id: "glass-12", url: "/images/galleries/bulletproof-glass/glass-12.png", alt: "Commercial security glass" },
    ],
  },
  {
    id: "safes",
    title: "Any Type of Safes",
    slug: "safes",
    description:
      "From compact personal safes to massive vault systems. We provide any type of safe for residential, commercial, or institutional use with various security ratings.",
    coverImage: "/images/galleries/safes/safe-1.jpg",
    images: [
      { id: "safe-1", url: "/images/galleries/safes/safe-1.jpg", alt: "High-security safe" },
      { id: "safe-2", url: "/images/galleries/safes/safe-2.jpg", alt: "Commercial vault safe" },
      { id: "safe-3", url: "/images/galleries/safes/safe-3.jpg", alt: "Residential safe installation" },
      { id: "safe-4", url: "/images/galleries/safes/safe-4.jpg", alt: "Custom safe system" },
    ],
  },
];

export function getServiceBySlug(slug: string): ServiceCategory | undefined {
  return serviceCategories.find((cat) => cat.slug === slug);
}

export function getAllServiceSlugs(): string[] {
  return serviceCategories.map((cat) => cat.slug);
}
